# Generated by Django 5.2 on 2025-05-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDS_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacks',
            old_name='timestamp',
            new_name='created',
        ),
    ]
