# Generated by Django 5.2.1 on 2025-05-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntrusionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.CharField(max_length=100)),
                ('detected', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
